
package com.thomsonreuters.wokmws.cxf.auth;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "QueryException", targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com")
public class QueryExceptionException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private QueryException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public QueryExceptionException(String message, QueryException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public QueryExceptionException(String message, QueryException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.thomsonreuters.wokmws.cxf.auth.QueryException
     */
    public QueryException getFaultInfo() {
        return faultInfo;
    }

}
