-- DROP ALL
DROP TABLE TRANSACTION
DROP TABLE G_PRODUCT
DROP TABLE LOC_COMMENT
DROP TABLE G_BOARD
DROP TABLE ADDR_INFO
DROP TABLE G_MEMBER


-- TABLES
-- 회원 테이블
DROP TABLE GD_MEMBER
CREATE TABLE GD_MEMBER(
	ID VARCHAR2(30) PRIMARY KEY,
	PASSWORD VARCHAR2(30) NOT NULL,
	ADDR_CODE VARCHAR2(10) NOT NULL,
	ADDRESS_DETAIL 
	TEL VARCHAR2(18) NOT NULL,
	JOB VARCHAR2(18) NOT NULL
)

-- 주소 정보 테이블
DROP TABLE ADDR_INFO
CREATE TABLE ADDR_INFO(
	ADDR_CODE NUMBER PRIMARY KEY,
	LOC VARCHAR2(21) NOT NULL
)

-- 물려줄 물건 게시 단위 테이블
DROP TABLE G_BOARD
CREATE TABLE G_BOARD(
	BNO NUMBER PRIMARY KEY,
	TITLE VARCHAR2(50) NOT NULL,
	HIT NUMBER NOT NULL,
	TIME_POSTED DATE NOT NULL,
	ID VARCHAR2(30) NOT NULL,
	CONSTRAINT FK_BD_ID FOREIGN KEY(ID) REFERENCES G_MEMBER
)

-- 지역 후기 테이블
DROP TABLE LOC_COMMENT
CREATE TABLE LOC_COMMENT(
	CNO NUMBER PRIMARY KEY,
	TITLE VARCHAR2(50) NOT NULL,
	HIT NUMBER NOT NULL,
	TIME_POSTED DATE NOT NULL,
	ADDR_CODE NUMBER NOT NULL,
	ID VARCHAR2(30) NOT NULL,
	CONSTRAINT FK_COM_ID FOREIGN KEY(ID) REFERENCES G_MEMBER,
	CONSTRAINT FK_ADDR_CODE FOREIGN KEY(ADDR_CODE) REFERENCES ADDR_INFO
)

-- 물려줄 물건 테이블
DROP TABLE G_PRODUCT
CREATE TABLE G_PRODUCT(
	PNO NUMBER PRIMARY KEY,
	BNO NUMBER  NOT NULL,
	KIND VARCHAR2(18) NOT NULL,
	PCONTENT VARCHAR2(50) NOT NULL,
	ADDR_CODE NUMBER NOT NULL,
	CONSTRAINT FK_PRO_ADDR_CODE FOREIGN KEY(ADDR_CODE) REFERENCES ADDR_INFO,
	CONSTRAINT FK_BNO FOREIGN KEY(BNO) REFERENCES G_BOARD
)

-- 신청서 테이블
DROP TABLE APPLICATION
CREATE TABLE APPLICATION(
	ANO NUMBER PRIMARY KEY,
	REASON VARCHAR2(100) NOT NULL,
	ID VARCHAR2(30) NOT NULL,
	CONSTRAINT FK_APP_ID FOREIGN KEY(ID) REFERENCES G_MEMBER
)

-- 신청 내역 테이블
DROP TABLE TRANSACTION
CREATE TABLE TRANSACTION(
	TNO NUMBER PRIMARY KEY,
	PNO NUMBER NOT NULL,
	ANO NUMBER NOT NULL,
	CONSTRAINT FK_TRAN_PNO FOREIGN KEY(PNO) REFERENCES G_PRODUCT,
	CONSTRAINT FK_TRAN_ANO FOREIGN KEY(ANO) REFERENCES APPLICATION
)

-- SEQUENCES
DROP SEQUENCE B_SEQ
DROP SEQUENCE T_SEQ
DROP SEQUENCE P_SEQ
DROP SEQUENCE A_SEQ

-- B : BOARD / T : TRANSACTION / P : PRODUCT / A : APPLICATION
CREATE SEQUENCE B_SEQ
CREATE SEQUENCE T_SEQ
CREATE SEQUENCE P_SEQ
CREATE SEQUENCE A_SEQ

