/*
 * subject 	: 
 * date 	: 2019-03-07
 * author 	: 마규석
 * desc.	: 
 */




/*
 * subject 	: 
 * date 	: 2019-03-07
 * author 	: 김승신
 * desc.	: 
 */
DROP TABLE PROJ_CONNECTION;
DROP TABLE DIR;
DROP TABLE PROJECT;
DROP TABLE PROJ_STAT;

CREATE TABLE PROJ_STAT(
	PROJ_STAT_CODE INT AUTO_INCREMENT PRIMARY KEY,
	PROJ_STAT_DEF VARCHAR(16)
) DEFAULT CHARSET=utf8;

CREATE TABLE PROJECT(
	PROJ_ID INT AUTO_INCREMENT PRIMARY KEY,
	PROJ_NAME VARCHAR(128),
	PROJ_CALE_GUBUN VARCHAR(16),
	PROJ_SUBJECT VARCHAR(32),
	PROJ_DESC BLOB,
	PROJ_START_DATE DATE,
	PROJ_END_DATE DATE,
	PROJ_EXP_END_DATE DATE,
	PROJ_EXP_START_DATE DATE,
	PROJ_PROGRESS INT,
	PROJ_STAT_CODE INT,
	FOREIGN KEY (PROJ_STAT_CODE) REFERENCES PROJ_STAT (PROJ_STAT_CODE)
) DEFAULT CHARSET=utf8;

CREATE TABLE PROJ_CONNECTION(
	PART_USER_ID INT PRIMARY KEY,
	ROLL VARCHAR(32),
	PROJ_ID INT,
	FOREIGN KEY (PROJ_ID) REFERENCES PROJECT (PROJ_ID),
	FOREIGN KEY (PART_USER_ID) REFERENCES USER (USER_ID)
) DEFAULT CHARSET=utf8;

CREATE TABLE DIR(
	DIR_ID INT AUTO_INCREMENT PRIMARY KEY,
	DIR_NAME VARCHAR(128),
	CREATE_DATE DATE,
	PROJ_ID INT,
	PARENT_DIR_ID INT,
	FOREIGN KEY (PROJ_ID) REFERENCES PROJECT (PROJ_ID),
	FOREIGN KEY (PARENT_DIR_ID) REFERENCES DIR (DIR_ID)
) DEFAULT CHARSET=utf8;

/*
 * subject 	: 
 * date 	: 2019-03-07
 * author 	: 김윤상
 * desc.	: 
 */