
package com.thomsonreuters.wokmws.v3.woksearchlite;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WokSearchLiteService", targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com", wsdlLocation = "http://search.webofknowledge.com/esti/wokmws/ws/WokSearchLite?wsdl")
public class WokSearchLiteService
    extends Service
{

    private final static URL WOKSEARCHLITESERVICE_WSDL_LOCATION;
    private final static WebServiceException WOKSEARCHLITESERVICE_EXCEPTION;
    private final static QName WOKSEARCHLITESERVICE_QNAME = new QName("http://woksearchlite.v3.wokmws.thomsonreuters.com", "WokSearchLiteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://search.webofknowledge.com/esti/wokmws/ws/WokSearchLite?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WOKSEARCHLITESERVICE_WSDL_LOCATION = url;
        WOKSEARCHLITESERVICE_EXCEPTION = e;
    }

    public WokSearchLiteService() {
        super(__getWsdlLocation(), WOKSEARCHLITESERVICE_QNAME);
    }

    public WokSearchLiteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WOKSEARCHLITESERVICE_QNAME, features);
    }

    public WokSearchLiteService(URL wsdlLocation) {
        super(wsdlLocation, WOKSEARCHLITESERVICE_QNAME);
    }

    public WokSearchLiteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WOKSEARCHLITESERVICE_QNAME, features);
    }

    public WokSearchLiteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WokSearchLiteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WokSearchLite
     */
    @WebEndpoint(name = "WokSearchLitePort")
    public WokSearchLite getWokSearchLitePort() {
        return super.getPort(new QName("http://woksearchlite.v3.wokmws.thomsonreuters.com", "WokSearchLitePort"), WokSearchLite.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WokSearchLite
     */
    @WebEndpoint(name = "WokSearchLitePort")
    public WokSearchLite getWokSearchLitePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://woksearchlite.v3.wokmws.thomsonreuters.com", "WokSearchLitePort"), WokSearchLite.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WOKSEARCHLITESERVICE_EXCEPTION!= null) {
            throw WOKSEARCHLITESERVICE_EXCEPTION;
        }
        return WOKSEARCHLITESERVICE_WSDL_LOCATION;
    }

}
