
package com.thomsonreuters.wokmws.v3.woksearchlite;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WokSearchLite", targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com")
@XmlSeeAlso({
    com.thomsonreuters.wokmws.v3.woksearch.ObjectFactory.class,
    com.thomsonreuters.wokmws.v3.woksearchlite.ObjectFactory.class
})
public interface WokSearchLite {


    /**
     * 
     * @param retrieveParameters
     * @param queryId
     * @return
     *     returns com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults
     * @throws InvalidInputExceptionException
     * @throws QueryExceptionException
     * @throws AuthenticationExceptionException
     * @throws SessionExceptionException
     * @throws ESTIWSExceptionException
     * @throws InternalServerExceptionException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieve", targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearchlite.Retrieve")
    @ResponseWrapper(localName = "retrieveResponse", targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveResponse")
    public SearchResults retrieve(
        @WebParam(name = "queryId", targetNamespace = "")
        String queryId,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        RetrieveParameters retrieveParameters)
        throws AuthenticationExceptionException, ESTIWSExceptionException, InternalServerExceptionException, InvalidInputExceptionException, QueryExceptionException, SessionExceptionException
    ;

    /**
     * 
     * @param queryParameters
     * @param retrieveParameters
     * @return
     *     returns com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults
     * @throws InvalidInputExceptionException
     * @throws QueryExceptionException
     * @throws AuthenticationExceptionException
     * @throws SessionExceptionException
     * @throws ESTIWSExceptionException
     * @throws InternalServerExceptionException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearchlite.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearchlite.SearchResponse")
    public SearchResults search(
        @WebParam(name = "queryParameters", targetNamespace = "")
        QueryParameters queryParameters,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        RetrieveParameters retrieveParameters)
        throws AuthenticationExceptionException, ESTIWSExceptionException, InternalServerExceptionException, InvalidInputExceptionException, QueryExceptionException, SessionExceptionException
    ;

    /**
     * 
     * @param uid
     * @param queryLanguage
     * @param databaseId
     * @param retrieveParameters
     * @return
     *     returns com.thomsonreuters.wokmws.v3.woksearchlite.SearchResults
     * @throws InvalidInputExceptionException
     * @throws QueryExceptionException
     * @throws AuthenticationExceptionException
     * @throws SessionExceptionException
     * @throws ESTIWSExceptionException
     * @throws InternalServerExceptionException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveById", targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveById")
    @ResponseWrapper(localName = "retrieveByIdResponse", targetNamespace = "http://woksearchlite.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearchlite.RetrieveByIdResponse")
    public SearchResults retrieveById(
        @WebParam(name = "databaseId", targetNamespace = "")
        String databaseId,
        @WebParam(name = "uid", targetNamespace = "")
        List<String> uid,
        @WebParam(name = "queryLanguage", targetNamespace = "")
        String queryLanguage,
        @WebParam(name = "retrieveParameters", targetNamespace = "")
        RetrieveParameters retrieveParameters)
        throws AuthenticationExceptionException, ESTIWSExceptionException, InternalServerExceptionException, InvalidInputExceptionException, QueryExceptionException, SessionExceptionException
    ;

}
