
package com.thomsonreuters.wokmws.v3.woksearchlite;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidInputException", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com")
public class InvalidInputExceptionException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidInputException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidInputExceptionException(String message, InvalidInputException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidInputExceptionException(String message, InvalidInputException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.thomsonreuters.wokmws.v3.woksearchlite.InvalidInputException
     */
    public InvalidInputException getFaultInfo() {
        return faultInfo;
    }

}
